#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TipperKit.Resource", IsApplication=true)]

namespace TipperKit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Cyl = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DataS1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Ram = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RodDiameter = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Tanks = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int TipperDrawing = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int TonForce = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int WeightsMeasures = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06004a
			public const int Back = 2131099722;
			
			// aapt resource value: 0x7f060003
			public const int ClientNumber = 2131099651;
			
			// aapt resource value: 0x7f06007a
			public const int GenerateReport = 2131099770;
			
			// aapt resource value: 0x7f060004
			public const int Go = 2131099652;
			
			// aapt resource value: 0x7f060048
			public const int Message = 2131099720;
			
			// aapt resource value: 0x7f060017
			public const int Output = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Output1 = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int Output10 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int Output11 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Output12 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int Output13 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int Output14 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int Output15 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int Output16 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int Output17 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int Output18 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int Output19 = 2131099691;
			
			// aapt resource value: 0x7f060019
			public const int Output2 = 2131099673;
			
			// aapt resource value: 0x7f06002c
			public const int Output20 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int Output21 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int Output24 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int Output25 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int Output26 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int Output27 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int Output28 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int Output29 = 2131099699;
			
			// aapt resource value: 0x7f06001b
			public const int Output3 = 2131099675;
			
			// aapt resource value: 0x7f060034
			public const int Output30 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int Output31 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int Output32 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int Output33 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int Output34 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int Output35 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int Output36 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int Output37 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int Output38 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int Output39 = 2131099709;
			
			// aapt resource value: 0x7f06001c
			public const int Output4 = 2131099676;
			
			// aapt resource value: 0x7f06003e
			public const int Output40 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int Output41 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int Output42 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int Output44 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int Output46 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int Output47 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int Output48 = 2131099716;
			
			// aapt resource value: 0x7f060016
			public const int Output49 = 2131099670;
			
			// aapt resource value: 0x7f060066
			public const int Output491 = 2131099750;
			
			// aapt resource value: 0x7f060068
			public const int Output492 = 2131099752;
			
			// aapt resource value: 0x7f06006a
			public const int Output493 = 2131099754;
			
			// aapt resource value: 0x7f06006c
			public const int Output494 = 2131099756;
			
			// aapt resource value: 0x7f06006e
			public const int Output495 = 2131099758;
			
			// aapt resource value: 0x7f06001d
			public const int Output5 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int Output6 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int Output7 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int Output8 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int Output9 = 2131099681;
			
			// aapt resource value: 0x7f060064
			public const int OutputA1 = 2131099748;
			
			// aapt resource value: 0x7f060072
			public const int OutputA10 = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int OutputA11 = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int OutputA12 = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int OutputA13 = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int OutputA14 = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int OutputA15 = 2131099767;
			
			// aapt resource value: 0x7f060065
			public const int OutputA2 = 2131099749;
			
			// aapt resource value: 0x7f060067
			public const int OutputA3 = 2131099751;
			
			// aapt resource value: 0x7f060069
			public const int OutputA4 = 2131099753;
			
			// aapt resource value: 0x7f06006b
			public const int OutputA5 = 2131099755;
			
			// aapt resource value: 0x7f06006d
			public const int OutputA6 = 2131099757;
			
			// aapt resource value: 0x7f06006f
			public const int OutputA7 = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int OutputA8 = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int OutputA9 = 2131099761;
			
			// aapt resource value: 0x7f060052
			public const int OutputPartC = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int OutputPartT = 2131099731;
			
			// aapt resource value: 0x7f060079
			public const int Recalculate = 2131099769;
			
			// aapt resource value: 0x7f06005e
			public const int SRH6L = 2131099742;
			
			// aapt resource value: 0x7f060061
			public const int SSH10L = 2131099745;
			
			// aapt resource value: 0x7f06004b
			public const int Send = 2131099723;
			
			// aapt resource value: 0x7f060055
			public const int Sentance = 2131099733;
			
			// aapt resource value: 0x7f060045
			public const int button1 = 2131099717;
			
			// aapt resource value: 0x7f06004f
			public const int button2 = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int button3 = 2131099728;
			
			// aapt resource value: 0x7f060012
			public const int devSwitch = 2131099666;
			
			// aapt resource value: 0x7f060046
			public const int editText1 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int editText2 = 2131099719;
			
			// aapt resource value: 0x7f06004c
			public const int editText3 = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int editText4 = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int editText5 = 2131099726;
			
			// aapt resource value: 0x7f060059
			public const int frameLayout1 = 2131099737;
			
			// aapt resource value: 0x7f060007
			public const int imageView1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int imageView2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageView3 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageView4 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imageView5 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int imageView6 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageView7 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageView8 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout2 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout3 = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout4 = 2131099674;
			
			// aapt resource value: 0x7f060049
			public const int linearLayout5 = 2131099721;
			
			// aapt resource value: 0x7f060078
			public const int linearLayout6 = 2131099768;
			
			// aapt resource value: 0x7f060051
			public const int linearLayout7 = 2131099729;
			
			// aapt resource value: 0x7f060056
			public const int linearLayout8 = 2131099734;
			
			// aapt resource value: 0x7f060063
			public const int linearLayout9 = 2131099747;
			
			// aapt resource value: 0x7f060054
			public const int overallApplication = 2131099732;
			
			// aapt resource value: 0x7f060011
			public const int sampleSwitch = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int scrollView1 = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int space1 = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int testingSwitch = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int textView2 = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int textView3 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int textView4 = 2131099653;
			
			// aapt resource value: 0x7f06005a
			public const int textViewA = 2131099738;
			
			// aapt resource value: 0x7f060062
			public const int textViewH = 2131099746;
			
			// aapt resource value: 0x7f060058
			public const int textViewa = 2131099736;
			
			// aapt resource value: 0x7f060057
			public const int textViewaasdg = 2131099735;
			
			// aapt resource value: 0x7f06005b
			public const int textViewb = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int textViewc = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int textViewd = 2131099741;
			
			// aapt resource value: 0x7f06005f
			public const int textViewf = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int textViewg = 2131099744;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthenticationScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataSheetLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DetailedOutputLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GenerateReportLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OutputLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TipperKitTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
